### ISSUE TITLE
Uploading

### ISSUE THREAD

**Issue by OneOfEleven** [DualTachyon/uv-k5-firmware#12]
Hello

Great project !

I was wondering if the compiled **firmware.bin** needs any processing before uploading to the radios CPU ?  .. ie, encrypting or such like.

Also, what about **sram-overlay.bin**, does this need to somehow be used in some way ?

Thank you

**Comment by DualTachyon** [comment]
I use flashing by SWD using OpenOCD. I believe most people use "k5prog" to flash the firmware.bin. I have not used it myself, but I believe it's a direct flash with it.

sram-overlay.bin is automatically embedded into firmware.bin by the Makefile, you do not need to concern yourself with it.

**Comment by OneOfEleven** [comment]
ah, I thought you might use the SWD port/pins.

I assumed the 'k5prog' only read/wrote from/to an eeprom chip on the board rather than the CPU's program flash, I've not looked at that, I'll check it out.

**Comment by DualTachyon** [comment]
k5prog can write to the flash, but only when the K5 is in bootloader mode. (Press and hold PTT before turning the radio on).

**Comment by OneOfEleven** [comment]
Thank you replying and for the info.

Now currently creating a little windows GUI app using the k5prog code to allow easy reading/writing from/to the radio in windows.

Looking forward to using your firmware in the radio, and also adding to it for usefulness.

Looks like your using the normal ARM M0 compiler for the asian CPU, which is cool.

**Comment by OneOfEleven** [comment]
Have now done a simple windows GUI version of k5prog so that any windows users out there can now easily upload the compiled firmware.bin to the radio ..

https://github.com/OneOfEleven/k5prog-win

Should hopefully increase your audience/users !

All credit to Jacek (k5prog) and you guys.

**Comment by DualTachyon** [comment]
I gave your link to the people in Telegram groups, and some have already tested it successfully. Thanks for providing this tool.
