### ISSUE TITLE
Battery save mode and NOAA scan mode overlaps

### ISSUE THREAD

**Issue by fagci** [DualTachyon/uv-k5-firmware#20]
Coz not updating state in statusbar after it changes.

![image](https://github.com/DualTachyon/uv-k5-firmware/assets/8795970/3c9e10c6-285a-489b-bd20-11ac3529c49a)

**Comment by Tunas1337** [comment]
I'm not sure why NS is up there in the first place. It should be down where the power level for the channel is.

**Comment by fagci** [comment]
@Tunas1337 right place (in stock fw). But battery save mode will not enable when NS mode on...

**Comment by DualTachyon** [comment]
Fixed.
