### ISSUE TITLE
New non-serif font 

### ISSUE THREAD

**Issue by mbgroot** [DualTachyon/uv-k5-firmware#22]
I would like to suggest a sans serif font, Terminus. But I can't find the encoding used in the font.c file
Can you tell me about the encoding?

**Comment by DualTachyon** [comment]
1 byte corresponds to 8 vertical bytes, so if you draw 8 bytes at (x=0, y=0) with 0x01, 0x02, 0x04, 0x08, .. 0x80, you will get:

0x01 -> x = 0, y = 7
0x02 -> x = 1, y = 6
0x04 -> x = 2, y = 5
0x08 -> x = 3, y = 4
..
0x80 -> x = 7, y = 0
