### ISSUE TITLE
Configuration upload/download

### ISSUE THREAD

**Issue by OneOfEleven** [DualTachyon/uv-k5-firmware#23]
Hi

It's not really an issue but was just wondering if you intend to add the config serial upload/download ability at some point in the future. Judging by the current compiled .bin size it's going to be quite a squeeze to fit it in.

**Comment by DualTachyon** [comment]
Sometime soon. Getting the other features stable is the current priority. Currently, everything seems stable enough but not many people have been testing the firmware yet.

**Comment by OneOfEleven** [comment]
oh right, cool.

I've been trying it on and off, noticed the odd small bug here and there at times but assumed you'd got a team hidden away testing for you so never reported anything.

In that case I'll report back any small bugs I notice then for you if you like. I do know people are looking forward to your open firmware, even if they're not saying so. It's opening up the ability to get the radio to do whatever we want (within reason) !

**Comment by DualTachyon** [comment]
Feel free to post new issues if you find bugs. We use Telegram groups to chat, but I don't get a lot of bug reports. There were a few filed and I got those fixed.

https://t.me/quansheng_uvk5_en_dev/16195

**Comment by DualTachyon** [comment]
With the last commit a few minutes ago, I consider the re-implementation of the firmware complete. Everything is included except the following some factory calibration checks. If a device didn't go through calibration procedure, the original K5 refuses to run. Originally I thought it was a piracy/clone check, but I found that it is there to prevent no-calibration radio doing bad things with RF.

I didn't implement it for 2 reasons: people using this firmware should already have a calibrated unit and because there is no space left in the flash after the last commit.

**Comment by DualTachyon** [comment]
Unfortunately 12.3.1 is too new... I'm using the default arm compiler of Ubuntu 22.04:

gcc version 10.3.1 20210621 (release) (15:10.3-2021.07-4)

You can get the same compiler here: https://developer.arm.com/downloads/-/gnu-rm
(Ignore the deprecated message and the 10.3-2021.10 version is fine too).

Currently, I'm in cleaning up phase where I rename variables/functions to proper names.
For actual improvements and features, development will happen outside this repository. This repo is mainly informational and to be a reference point. I will soon post some links of improved firmware on the front page.

**Comment by DualTachyon** [comment]
Try your original compiler with this change:

-       $(CC) $(CFLAGS) $(INC) -c $< -o $@
+       $(CC) $(CFLAGS) -flto $(INC) -c $< -o $@

(Don't put -flto in CFLAGS, it will fail).

**Comment by DualTachyon** [comment]
I pushed this lto change to latest.

**Comment by DualTachyon** [comment]
I removed the LTO commit. It break the firmware in strange ways.

**Comment by OneOfEleven** [comment]
I removed the new compile from my windows ubuntu install and installed the v10 you mentioned. It now compiles OK :)

**Comment by OneOfEleven** [comment]
You'll have to mention the required compiler version in your README.MD I think so that people will be able to compile OK

**Comment by OneOfEleven** [comment]
If it helps others this is the ubuntu command line list I used to install the correct compiler version in windows wsl2 ..

curl -Lo gcc-arm-none-eabi.tar.bz2 https://developer.arm.com/-/media/Files/downloads/gnu-rm/10.3-2021.10/gcc-arm-none-eabi-10.3-2021.10-x86_64-linux.tar.bz2
sudo mkdir /opt/gcc-arm-none-eabi
sudo tar xf gcc-arm-none-eabi.tar.bz2 --strip-components=1 -C /opt/gcc-arm-none-eabi
echo 'export PATH=$PATH:/opt/gcc-arm-none-eabi/bin' | sudo tee -a /etc/profile.d/gcc-arm-none-eabi.sh
source /etc/profile
arm-none-eabi-gcc --version
rm -rf gcc-arm-none-eabi.tar.bz2

**Comment by OneOfEleven** [comment]
When I upload the radio configuration back into the radio, I send a 'reboot' packet at the end but your firmware doesn't reboot the radio, the quangsheng firmware does though.

write_eeprom  offset 1F80  len 128
tx crc_ok 1
tx obfuscated [148] AB CD 8C 00 0B 69 9C E6 AE 8E 8D 41 4B 0C 82 24 10 0B E7 93 0E 93 EB 19 2A 91 4B 40 71 35 F9 4E EC FC 16 7F E9 93 EB 19 D1 6E F2 BF DE CA 2A BF EC FC 16 7F E9 93 EB 19 D1 6E F2 BF DE CA 2A BF EC FC 16 7F E9 93 EB 19 D1 6E F2 BF DE CA 2A BF EC FC 16 7F E9 93 EB 19 D1 6E F2 BF DE CA 2A BF EC FC 16 7F E9 93 EB 19 D1 6E F2 BF DE CA 2A BF EC FC 16 7F E9 93 EB 19 D1 6E F2 BF DE CA 2A BF EC FC 16 7F E9 93 EB 19 D1 6E F2 BF DE CA 2A BF 65 0A DC BA
tx clear      [140]             1D 05 88 00 80 1F 80 01 6A 39 57 64 03 08 0E 13 18 FF FF FF 04 00 46 00 50 00 2C 0E FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF 9A 00
write EEPROM complete

sending reboot radio ..
tx crc_ok 1
tx obfuscated [ 16] AB CD 08 00 CB 69 14 E6 2C 91 0D 40 6F C1 DC BA
tx clear      [  8]             DD 05 00 00 02 00 00 00 16 00

'COM8' closed

**Comment by DualTachyon** [comment]
It's a known issue that I need to fix. Thanks the report.

**Comment by DualTachyon** [comment]
Try the latest "git pull".

**Comment by OneOfEleven** [comment]
ah, you've fixed it, the reboot command now works :)

You've done an amazing job writing the source, I don't know how you've managed to do so like this without a set of schematics and detailed info about v2.01.27.

Well done !!

There is a small difference in the reply from the initial packet sent to the radio (command 0x0514), the 'challenge' data is all zero's with your firmware ..

'COM8' opened at 38400 Baud
Uploading configuration data to the radio ..
sending k5_hello ..

  firmware version: 'Open Edition FW'
has custom AES key: no
 is in lock screen: no
         challenge: 00 00 00 00

The original firmware is like this ..

'COM8' opened at 38400 Baud

Downloading configuration data from the radio ..

sending k5_hello ..

  firmware version: 'k5_2.01.26'
has custom AES key: no
 is in lock screen: no
         challenge: 9D 06 DA 55

I suspect the AES challenge is a random set of initial values, I've yet to look at that part of your code.

Thank you for what you've done, amazing !

**Comment by DualTachyon** [comment]
0 challenge is normal. I didn't want to implement "srand+rand" functions because they are only used for this purpose (and also not much flash space left). It shouldn't affect anything unless the PC software checks for zero.
