### ISSUE TITLE
Compiling directly in windows

### ISSUE THREAD

**Issue by OneOfEleven** [DualTachyon/uv-k5-firmware#28]
I've modified your makefile very slightly that allows the firmware to fully compile in windows (on the command line), ie no longer need windows users to install a virtual a linux OS just to compile it ..

was ..

TOP := $(shell pwd)

now ..

ifeq ($(OS),Windows_NT)
	# windows
	TOP := $(dir $(realpath $(lastword $(MAKEFILE_LIST))))
else
	# non-windows
	TOP := $(shell pwd)
endif

**Comment by DualTachyon** [comment]
I committed this change.
