### ISSUE TITLE
Mic gain bug ?

### ISSUE THREAD

**Issue by OneOfEleven** [DualTachyon/uv-k5-firmware#33]
I'm not certain but I think there is a bug in board.c "BOARD_EEPROM_LoadMoreSettings(void)" ..

currently ..
	gEeprom.MIC_SENSITIVITY_TUNING = (Mic >= 32) ? Mic : 15; 

probably should be ? ..
	gEeprom.MIC_SENSITIVITY_TUNING = (Mic <= 31) ? Mic : 31;

**Comment by DualTachyon** [comment]
The current is correct. It selects a medium value if the eeprom value is too high (due to 0xFF or bug).

From Ghidra below:

        if (0x1f < (byte)MicSensitivity) {
                MicSensitivity = CONCAT31(MicSensitivity._1_3_,0xf);
        }
        gEeprom.MIC_SENSITIVITY_TUNING = (byte)MicSensitivity;

**Comment by OneOfEleven** [comment]
no, it's setting a medium value if the value is NOT too big (ie if the eeprom value is valid).

it's setting a value that IS too big if the eeprom value is to big (0xff).

**Comment by DualTachyon** [comment]
Oh I see it now. I'll fix it.

**Comment by DualTachyon** [comment]
https://github.com/DualTachyon/uv-k5-firmware/commit/4f3ce97f25b95d20457e8925f4b776344b85eaf6

**Comment by OneOfEleven** [comment]
Looks good !

**Comment by DualTachyon** [comment]
I don't know if I mentioned it already, but the firmware implementation is complete. I do not consider some "uncalibrated" UART commands as useful or needed. Only thing left are some better renaming and bug fixes.

**Comment by OneOfEleven** [comment]
Yes I think I did see you mention it being complete now (apart from the odd fix).

Understand about the uncalibrated part, as it is is just fine I think, as you say, peoples radios already have their correct calibration data stored.

I was thinking about adding a calibration option to my windows programmer to let people do the calibrations if they really wanted too, but for now I'll leave it.

**Comment by OneOfEleven** [comment]
> I don't know if I mentioned it already, but the firmware implementation is complete. I do not consider some "uncalibrated" UART commands as useful or needed. Only thing left are some better renaming and bug fixes.

I've now uploaded the customization I'm making for those interested ..

https://github.com/OneOfEleven/uv-k5-firmware-custom

**Comment by DualTachyon** [comment]
Thanks, I added your link to the README.md and shared it in Telegram groups.

**Comment by OneOfEleven** [comment]
Thanks ! .. it may help someone out there.
