### ISSUE TITLE
Menu confirmation bug

### ISSUE THREAD

**Issue by OneOfEleven** [DualTachyon/uv-k5-firmware#35]
If I go into a menu item and go to execute say the DEL-CH, it brings up the are you "Sure" confirmation OK,, but if you decide to back out by pressing the exit button, the are you "Sure" confirmation remains.

I'm guessing the 'gAskForConfirmation' variable is not being cleared when the key_exit event is triggered ? .. or such like

**Comment by DualTachyon** [comment]
I will investigate.

**Comment by DualTachyon** [comment]
I checked Ghidra and all gAskForConfirmation are accounted for in OEFW. I'll do some debug with SWD.

**Comment by DualTachyon** [comment]
It happens in the original FW also, so this looks like a bug with QS and not one from OEFW.
I clear gAsk in the exit menu and it behaves as you would expect.

static void MENU_Key_EXIT(bool bKeyPressed, bool bKeyHeld)
...
                                        gInputBoxIndex = 0;
                                        gFlagRefreshSetting = true;
                                        gAnotherVoiceID = VOICE_ID_CANCEL;
+                                       gAskForConfirmation = 0;   <<<<<<< HERE
                                } else {

**Comment by OneOfEleven** [comment]
Yes that's the same solution as I arrived at too, it fixes it.
