### ISSUE TITLE
bug ?

### ISSUE THREAD

**Issue by OneOfEleven** [DualTachyon/uv-k5-firmware#37]
Not sure what's what here at the moment ..

radio.c file line 313 ..

`
	Frequency = pRadio->ConfigRX.Frequency;
	if (Frequency < gLowerLimitFrequencyBandTable[Band]) {
		pRadio->ConfigRX.Frequency = gLowerLimitFrequencyBandTable[Band];
	} else if (Frequency > gUpperLimitFrequencyBandTable[Band]) {
		pRadio->ConfigRX.Frequency = gUpperLimitFrequencyBandTable[Band];
	} else if (Channel >= FREQ_CHANNEL_FIRST) {
		pRadio->ConfigRX.Frequency = FREQUENCY_FloorToStep(pRadio->ConfigRX.Frequency, gEeprom.VfoInfo[VFO].StepFrequency, gLowerLimitFrequencyBandTable[Band]);
	}
	pRadio->ConfigRX.Frequency = Frequency;
`

you're maybe setting "pRadio->ConfigRX.Frequency" with one of the IF's, but then wiping it out on the last line ?

**Comment by OneOfEleven** [comment]
Would this be the correct code ? ..

`
	Frequency = pRadio->ConfigRX.Frequency;
	if (Frequency < gLowerLimitFrequencyBandTable[Band])
		Frequency = gLowerLimitFrequencyBandTable[Band];
	else
	if (Frequency > gUpperLimitFrequencyBandTable[Band])
		Frequency = gUpperLimitFrequencyBandTable[Band];
	else
	if (Channel >= FREQ_CHANNEL_FIRST)
		Frequency = FREQUENCY_FloorToStep(Frequency, gEeprom.VfoInfo[VFO].StepFrequency, gLowerLimitFrequencyBandTable[Band]);
	pRadio->ConfigRX.Frequency = Frequency;
`

**Comment by DualTachyon** [comment]
You are right. I didn't clean that one correctly. I pushed the commit just now.
