### ISSUE TITLE
Backlight duration longer than stock, menu mode does not disable backlight and does not automatically exit

### ISSUE THREAD

**Issue by rakenrowl7** [DualTachyon/uv-k5-firmware#39]
I flashed the 9-10 packed using QS portable updater v1.1.12, and noticed that the backlight duration is longer than what i set it to prior to flashing. it was set to one second, but using OEFW it seems to be around 11 seconds. I then flashed the v27 provided in https://github.com/amnemonic/Quansheng_UV-K5_Firmware/blob/main/firmware/k5_v2.01.27_flashable.bin to compare it to, and the backlight properly turned off. i used a stopwatch on my phone and all options seems to have a +10 second of backlight on.

Another issue is when i stay on menu mode, it usually follows the backlight duration set, and exits back to standby mode after several seconds. Using OEFW it seems to be stuck on menu and the backlight does not turn off.

**Comment by DualTachyon** [comment]
Thanks for the report. I fixed it and you can find the latest binary here:

https://github.com/DualTachyon/uv-k5-firmware/releases/tag/2023-09-11-fixes

**Comment by rakenrowl7** [comment]
it works now, thanks for the update
