### ISSUE TITLE
Scanlist with priority channels defined does not scan other channels 

### ISSUE THREAD

**Issue by OK2MOP** [DualTachyon/uv-k5-firmware#51]
Hello,
I was not able to identify the offending code yet, but the original firmware will go through scanlist with both normal and priority channels in a a pattern intermixing priority channel(s) with normal ones (say P1 P2 N1 P1 P2 N2 etc.). 

In the open firmware, only priority channels are scanned if defined. If no priority channels are defined, the scanlist will work and loop through non-priority channels.

**Comment by OK2MOP** [comment]
Unfortunately, the problem in uploaded files persists (). If needed, I can supply some sample codeplug with scanlists, in which format then (k5prog dump, Chirp save file, stock codeplug tool format)? They are easy to define in stock software, in Chirp one has to go into browser window with channel attributes and manually change is_scanlist1 or is_scanlist2 to 1.

I will try to build the firmware by myself from the scanlist branch and test again just in case.

**Comment by OneOfEleven** [comment]
Just having a play now to see if I can spot it. Not used priority scanning yet.

**Comment by OK2MOP** [comment]
Here are the factory settings in all 3 formats to play with if neccessary. Scanlist 1 contains priority channels, Scanlist 2 is "normal". 
[factory_scanlist_test.zip](https://github.com/DualTachyon/uv-k5-firmware/files/12748311/factory_scanlist_test.zip)

**Comment by OneOfEleven** [comment]
Select any channel, then start normal scanning (F-key then */scan key).

It should scan through both priority and normal channels that have scan enabled

**Comment by OneOfEleven** [comment]
There are just 2 priority channels (they each simply point to chosen normal channels)

**Comment by OK2MOP** [comment]
Hello, I can confirm the fix is working now and the issue can be probably closed after porting it to main at some time

**Comment by OneOfEleven** [comment]
Yes it does seem to work :)

**Comment by OK2MOP** [comment]
Yes, I have already found out and closed the issue because of that. I found out it is even ported to [OneOfEleven's](https://github.com/OneOfEleven) firmware which I use right now.

Thanks all of you for your great work in rewriting the firmware as OpenSource and making it more usable.

**Comment by OneOfEleven** [comment]
There's no way to disable the priority channels in the menu it seems once the PC software sets them, will sort that out.

**Comment by OneOfEleven** [comment]
a limitation sorry. No way for user to disable the priority channels when scanning.
