### ISSUE TITLE
DTMF decoding shouldn't allow squelch to open unless call received

### ISSUE THREAD

**Issue by egzumer** [DualTachyon/uv-k5-firmware#64]
I don't know if you want to pursue that, but there is a difference between the original firmware and your version. When DTMF decoding is active the speaker should turn on only when active call is received. This does work on QS v26 and v31. If I upload your latest main version the radio receives the transmission as normal and speaker activates without receiving a call.

**Comment by DualTachyon** [comment]
If it is a bug in OEFW versus the original, then I will pursue it.
DTMF has been a contentious area in the past due to me not knowing how to use it properly.
Ghidra has some issues decompiling parts of it.

Can you give me simple steps to reproduce it ? I have 2 K5s I can reflash to test original and OEFW.

**Comment by egzumer** [comment]
You simply turn on the `D-DCD` menu option, that's it. 
On incoming transmission the green led should light up, but the audio path should stay closed.
To make a call you dial 102*103. This means 103 calling 102. 102 is default ANI ID on all radios. Only then the you should hear audio.

**Comment by OneOfEleven** [comment]
D-RESP

**Comment by egzumer** [comment]
D-RESP is for the radio to respond back on the RF path (or by a tone through the speaker), different thing

**Comment by DualTachyon** [comment]
Turned out to be simpler than anticipated. Thanks for the report.

I updated all 3 branches.

**Comment by DualTachyon** [comment]
I incorrectly simplified a big pile of if checks that were In Ghidra and I placed the return on the wrong branch.

**Comment by DualTachyon** [comment]
Hmm but that kills audio on normal reception. I must be missing something.

**Comment by egzumer** [comment]
Thank you. You've got some interesting skills, didn't know such things are possible. I'm not really surprised that russians ask who gave you the code. Great job man :)

**Comment by DualTachyon** [comment]
The fix I uploaded is definitely correct, I double checked. There must be a second bug somewhere else. Ill check it tomorrow, a bit late now. Can you confirm that you also get no audio when you PTT to OEFW?

**Comment by DualTachyon** [comment]
I've been doing this for a very long time (since the very early 90s) because there was not much else to do when you're stuck in a remote village in the middle of nowhere by the mountains surrounded by chickens, rabbits and cows. It was my way to learn stuff without access to books (there were none in the nearby city and I had no money anyway and nobody else has a computer).

Usually that kind of effort is worth a lot (think 6 digits), so there's not a lot of incentives for people to release stuff on GitHub for "free". I'm retired these days, so I have nothing to lose but my free time while having fun.

**Comment by egzumer** [comment]
I'll test this as soon as I can, I'm out today.

**Comment by DualTachyon** [comment]
Hmm. I flashed official 4.x back to my UV-5R+ and it behaves like you described is wrong. The speaker opens on receiving DTMF. And PTT to it also doesn't play audio.

**Comment by DualTachyon** [comment]
I flashed 2.1.27 stock to it and it does the same thing. Can you confirm in a new test which model with which firmware is sending DTMF to which modem with which firmware?

**Comment by DualTachyon** [comment]
It seems like DTMF acts like a DCS/CTCSS gate for receiving audio. Is that the expectation? If so, I don't seem to have a bug just a lack of understanding how this works.

**Comment by DualTachyon** [comment]
I just re-read your first post and I think that it works as you expect after the fix from last night. The rest I described was just my moment of "I don't much about DTMF calls" lack of clarity.

**Comment by egzumer** [comment]
Yes, it works correctly now.

The idea is you have multiple people with radios, each radio has its own unique ANI ID, all have DTMF decoding active.
You can call particular radio by dialing its ANI ID.
Only the person that you called should be able to hear you. When radio is being called it unlocks it's audio for a particular window of time set in D-HOLD menu. In that time conversation can be started, and participants can talk.

You can make a call even easier, press * to enter DTMF input box, dial 3 digit callee number, press PTT. QS radio will automatically append * and its own ANI ID at the end.
You can also make group calls by dialing the 3 digit ID with any number of digits replaced by #. Hash is a wildcard and any radio that has the rest of the digits matching with its own ANI ID will activate. In particular you can call ### in which case all radios should activate and be able to hear you.

**Comment by egzumer** [comment]
> there's not a lot of incentives for people to release stuff on GitHub for "free". I'm retired these days, so I have nothing to lose but my free time while having fun.

It's crazy how much effort went into that little cheap chinese radio :)
I was a C++ programmer for years, not a good one, but not the worst either :P, so I can tell what you did is rather unexpected, its thousands lines of code and even if most of the work is giving names to functions, constants and variables (I guess, don't really know), it is still something, how one can do that it's a mystery to me :)
I also have a lot off free time lately, and enjoy sitting on the firmware a little too much, I guess it's also the case with OneOfEleven :)
